import rawClubs from '../../data/clubs.json';

// Club dataset for the globe. data/clubs.json is a committed snapshot,
// (re)generated by `npm run build-clubs` (football-data.org + Wikidata);
// hand-fixes live in data/clubs-overrides.json.
export interface Club {
  id: string;              // '{iso2}-{slug}', e.g. 'nl-ajax'
  name: string;
  country: string;         // flagcdn-style code ('nl', 'gb-eng', ...), like UCLClub.flagCode
  city: string;
  competition: string;     // key of COMPETITIONS
  tier: number;            // professional level within the country (1, 2, ...)
  lat: number;             // stadium coordinates
  lng: number;
  stadium: { name: string; capacity: number | null };
  fdId: number | null;     // football-data.org team id; null ⇒ no fixtures
  crest: string | null;    // crest URL; null ⇒ generated initials badge
  colors?: [string, string];
  wikidataId?: string;
}

export interface CompetitionMeta {
  country: string;
  tier: number;
  label: string; // official competition name, not localized
}

export const COMPETITIONS: Record<string, CompetitionMeta> = {
  ED:  { country: 'nl',     tier: 1, label: 'Eredivisie' },
  KKD: { country: 'nl',     tier: 2, label: 'Keuken Kampioen Divisie' },
  PL:  { country: 'gb-eng', tier: 1, label: 'Premier League' },
  PD:  { country: 'es',     tier: 1, label: 'LaLiga' },
  BL1: { country: 'de',     tier: 1, label: 'Bundesliga' },
  SA:  { country: 'it',     tier: 1, label: 'Serie A' },
  FL1: { country: 'fr',     tier: 1, label: 'Ligue 1' },
};

export const clubs: Club[] = rawClubs as Club[];

const byId = new Map(clubs.map((c) => [c.id, c]));

export function getClub(id: string): Club | undefined {
  return byId.get(id);
}

// Country display names. Intl.DisplayNames covers ISO codes; football uses
// a few non-ISO flag codes (home nations) that need explicit labels.
const NON_ISO_COUNTRY: Record<string, Record<string, string>> = {
  'gb-eng': { nl: 'Engeland', en: 'England', es: 'Inglaterra' },
  'gb-sct': { nl: 'Schotland', en: 'Scotland', es: 'Escocia' },
  'gb-wls': { nl: 'Wales', en: 'Wales', es: 'Gales' },
  'gb-nir': { nl: 'Noord-Ierland', en: 'Northern Ireland', es: 'Irlanda del Norte' },
};

export function countryName(code: string, locale: string): string {
  const special = NON_ISO_COUNTRY[code]?.[locale] ?? NON_ISO_COUNTRY[code]?.en;
  if (special) return special;
  try {
    return new Intl.DisplayNames([locale], { type: 'region' }).of(code.toUpperCase()) ?? code;
  } catch {
    return code;
  }
}
